### PR TITLE
Added promises to translation versions

### PR DESCRIPTION
**Pull request by tavurth**
I didn't want to have to bump the translation version each time I change something in the database, so I've added a promise resolution checker to the `read` function.

Changes in the pull request:
- [x] Linted the code (There are still two errors, but before there were 18)
- [x] Added header comments (Might be useful for you)
- [x] Fixing missing Dev packages, the build wasn't working
- [x] Added a lint script which could be run before building
- [x] Upgraded packages (rollup)

Promise resolution works as follows:

```javascript
async function getVersion(language) {
    const { version } = await request(`/api/translations/${language}/version`);
    return version;
}

i18n
    .use(Backend)
    // ... other stuff
    .init({
        backend: {
            backends: [
                LocalStorageBackend, // primary
                XHR, // fallback
            ],
        },
        backendOptions: [
            {
                // ... other stuff

                // language versions
                versions: { en: getVersion('en'), ru: getVersion('ru') },
            },
        ],
    });
```

### CODE REVIEW

**Comment by tavurth** [comment]
Hmm, you're right. I wonder what's causing that large size increase for the `min.js`

**Comment by tavurth** [comment]
I checked out the current version of your repository, upgraded the scripts (build will not run on my machine otherwise) and then ran `yarn build`.
```
tavurth size-test > du -hs i18nextLocalStorageBackend.*
4.0K	i18nextLocalStorageBackend.js
4.0K	i18nextLocalStorageBackend.min.js
```

**Comment by tavurth** [comment]
I'm unable to get the build size to `1.8kb` on my machine. Checking out the repository here, and (after installing the missing packages) running build results in a `2.3kb` minified js file.

I guess it's the upgraded packages, but do you have any idea what might be causing the size increase?

**Comment by jamuhl** [comment]
Hm...no idea...honestly hoped it would get smaller with upgrades not the other way round :(

**Comment by tavurth** [comment]
Well without the promises I managed to golf it down to 2.1kb, would you be interested in a PR without?

**Comment by jamuhl** [comment]
Don't get me wrong...really appreciate it but i guess until needed i prefer having the size as small as possible. Plus it keeps things in same style as the other plugins i made beside this one.

**Comment by tavurth** [comment]
Not a problem, thought you might find the updates useful. I'll keep using our fork as it's in style with our code guidelines.

**Comment by vodanh109** [comment]
@tavurth any reason that u closed this pull request without waiting for merging into master branch. I think it's very useful

**Comment by jamuhl** [comment]
@vodanh109 read the comments

**Comment by vodanh109** [comment]
@jamuhl Sorry but i'm not so familiar with i18next. I tried with your suggestion for just wrap the full i18next init after getting version, but it seem that i18n hasn't been initialized before it can be used

**Comment by jamuhl** [comment]
@vodanh109 sorry i do not understand your problem...wait for the init callback before doing anything with i18next

**Comment by vodanh109** [comment]
@jamuhl sorry that I'm trying with React Native project, and I try with the expo example from https://github.com/i18next/react-i18next/tree/master/example/react-native-expo
and I have no idea how to wait for i18next to be initialized then initializing React Native App

**Comment by jamuhl** [comment]
using the hoc will assert waiting: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/pages/Home.js#L37 if set to wait

**Pull request closed without merging**
